name: shadowfitdemo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  camera: ^0.11.1
  image_picker: ^1.1.1
  http: ^1.1.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  uni_links: ^0.5.1
  google_mlkit_pose_detection: ^0.14.0
  path_provider: ^2.1.3
  image: ^4.2.0
  google_mlkit_commons: ^0.11.0
  just_audio: ^0.9.36

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/igris.png
    - assets/images/tank.png
    - assets/images/iron.png
    - assets/images/tusk.png
    - assets/images/kaisel.png
    - assets/images/beru.png
    - assets/images/greed.png
    - assets/images/bellion.png
    - assets/audio/music.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
